---
- hosts: frontEndServers
  tasks:
   - name: delete existing pm2 processes if running
     command: pm2 delete all
     ignore_errors: True

   - name: start pm2 process
     command: pm2 start /home/ubuntu/NodeTweet/nodeTweet/bin/www --name nodeTweet
       chdir=/home/ubuntu/NodeTweet/nodeTweet/bin/