---
- hosts: localServer
  connection: local
  tasks:
   - name: Reload Nginx
     service: name=nginx state=reloaded

- hosts: frontEndMasterServer
  tasks:
   - name: Restart rethinkdb
     service: name=rethinkdb state=restarted enabled=yes

- hosts: frontEndSlaveServers
  tasks:
   - name: Restart rethinkdb
     service: name=rethinkdb state=restarted enabled=yes

- hosts: frontEndServers
  tasks:
   - name: Reload Nginx
     service: name=nginx state=reloaded

   - name: delete existing pm2 processes if running
     command: pm2 delete all
     ignore_errors: True

   - name: start pm2 process
     command: pm2 start /home/ubuntu/NodeTweet/nodeTweet/bin/www --name nodeTweet
       chdir=/home/ubuntu/NodeTweet/nodeTweet/bin/