---
- hosts: localServer
  connection: local
  roles:
   - nginxLoadBalancerUpdate

- hosts: frontEndMasterServer
  roles:
   - rethinkdbMaster

- hosts: frontEndSlaveServers
  roles:
   - rethinkdbSlave

- hosts: frontEndServers
  roles:
   - gitPull

- hosts: frontEndMasterServer
  tasks:
   - name: initializeNodeWikiDB
     command: node /home/ubuntu/NodeTweet/nodeTweet/initializeNodeTweetDB.js

- hosts: frontEndServers
  roles:
   - nginxFrontEndServerUpdate
  tasks:
   - name: delete existing pm2 processes if running
     command: pm2 delete all
     ignore_errors: True

   - name: start pm2 process
     command: pm2 start /home/ubuntu/NodeTweet/nodeTweet/bin/www --name nodeTweet
       chdir=/home/ubuntu/NodeTweet/nodeTweet/bin/